/**
 * English spoken in the US
 */

$.Editable.LANGS['es_es'] = {
    translation: {
        "Bold": "Negrita",
        "Italic": "It\u00e1lica",
        "Underline": "Subrayado",
        "Strikethrough": "Tachado",
        "Font Size": "Tama\u00f1o de fuente",
        "Color": "Colores",
        "Background Color": "Fondo Color",
        "Text Color": "Texto Color",
        "Format Block": "Formato Block",
        "Normal": "Normal",
        "Paragraph": "P\u00e1rrafo",
        "Code": "Codigo",
        "Quote": "Cita",
        "Heading 1": "Encabezado 1",
        "Heading 2": "Encabezado 2",
        "Heading 3": "Encabezado 3",
        "Heading 4": "Encabezado 4",
        "Heading 5": "Encabezado 5",
        "Heading 6": "Encabezado 6",
        "Alignment": "Alinear",
        "Align Left": "Alinear Izquierda",
        "Align Center": "Alinear Centro",
        "Align Right": "Alinear Derecha",
        "Justify": "Justificar",
        "Numbered List": "Lista Numerada",
        "Bulleted List": "Bulleted List",
        "Indent Less": "Reducir sangr\u00eda",
        "Indent More": "Aumentar sangr\u00eda",
        "Select All": "Seleccionar todo",
        "Insert Link": "Insertar Link",
        "Insert Image": "Insertar Imagen",
        "Insert Video": "Insertar Video",
        "Undo": "Deshacer",
        "Redo": "Rehacer",
        "Show HTML": "Mostrar HTML",
        "Float Left": "Float Izquierda",
        "Float None": "Float None",
        "Float Right": "Float Derecha",
        "Replace Image": "Remplazar Imagen",
        "Remove Image": "Remover Imagen",
        "Title": "Titulo",
        "Insert image": "Insertar imagen",
        "Drop image": "Arrastrar imagen",
        "or click": "o click",
        "Enter URL": "Insertar URL",
        "Please wait!": "Favor esperar!",
        "Are you sure? Image will be deleted.": "Estas seguro? la imagen sera borrada",
        "UNLINK": "Desconectar",
        "Open in new tab": "Abrir una nueva tab",
        "Type something": "Escribir algo",
        "Cancel": "Cancelar",
        "OK": "OK",
        "Manage images": "Gestionar imagenes",
        "Delete": "Borrar",
        "Font Family": "Familia de fuentes",
        "Insert Horizontal Line": "Insertar Linea Horizontal"

    },
    direction: "ltr"
};